language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis
  - pip install coverage codecov
script:
  - tox
  - PYTHONPATH=${TRAVIS_BUILD_DIR} python -m coverage run --source xfail -m unittest discover
after_success:
  - codecov
