language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis
  - pip install coverage codecov
script:
  - tox
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then cd ${TRAVIS_BUILD_DIR} && coverage erase && python -m coverage run --source xfail -m unittest discover && coverage report && codecov; fi
